### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by dregge8** [brandon-barker/nodeminer#8]
When running "grunt serve" the webpage is not visible, express does not seem to be working. Has anyone used this recently?  It has the best WebUI I have seen and is several years old, would love to use.

**Comment by brandon-barker** [comment]
Hi @dregge8,

Thanks for the nice comment about the Web UI, I was not aware anyone was still using this as I haven't been mining in quite a few years. I'll look at this a little bit later when I get a gap in work and push up some updates if it's a quick fix.

I'm guessing many of the dependencies are out of date by now so will need a bit of tinkering. 

Cheers

**Comment by brandon-barker** [comment]
Have updated some conflicting and outdated dependency versions and run a clean install from my side, able to get the dashboard up and running again.

Have no rigs configured at the moment so cannot test all functionality still works, but it seems the socket.io connection is still stable, so it should all work.

Will try and get a rig configured in the coming weeks to do a full e2e test (can't promise anything here), but in the meantime please let me know if this fixed your issue.

**Comment by dregge8** [comment]
Hey @brandon-barker you certainly fixed the install!  After you corrected the dependencies or whatever you did I have no problem installing/running it with node V8.8.0

It pings my Antminer V9, which is using cgminer but none of the data is appearing.  Now that the project is running and configs are saving, I can take a look and maybe figure out why.

Thanks again!!
